name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.7
  - xarray
  - xrft
  - xgcm
  - scipy
  - dask
  - distributed
  - dask-kubernetes=0.10
  - dask-labextension=1.1
  - gcsfs
  - intake-xarray
  - zarr
  - matplotlib
  - numcodecs
  - python-blosc
  - lz4
  - nomkl
  - nbserverproxy
  - jupyter
  - jupyterlab=1.2
  - jupyterlab_launcher
  - jupyter_client
  - jupyter-server-proxy=1.2
  - ipywidgets
  - graphviz
  - nodejs
  - pip:
    - kubernetes
    - graphviz
    - xomega
