name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.7
  - xarray
  - xrft
  - xgcm
  - scipy
  - dask
  - distributed
  - dask-kubernetes
  - gcsfs=0.2.1
  - intake::intake-xarray
  - zarr
  - matplotlib
  - numcodecs
  - python-blosc
  - lz4
  - nomkl
  - nbserverproxy
  - jupyter
  - jupyterlab=0.35
  - jupyterlab_launcher
  - jupyter_client
  - ipywidgets
  - graphviz
  - nodejs
  - pip:
    - kubernetes
    - graphviz
    - xomega
